### ISSUE TITLE
Support for 3D video (no 360/180)

### ISSUE THREAD

**Issue by tomitrescak** [Unity-Technologies/SkyboxPanoramicShader#7]
Hi, thanks for the fantastic shader which is really helpful!.

We have a different need though and that is to project a 3D video on a plane ... think having a 3D movie playing in a cinema. How difficult would it be to modify this shader to do this? I know nothing about shader programming so I cannot attempt it myself.

Or, is there any other shader that I could use to project side-by-side or over-under video onto the plane and view it in my game?

Thanks!

**Comment by ErickSimoes** [comment]
I imagine two alternatives for you:
1. Create a 3D environment of a cinema, and in screen space display a 2D video (_as it is in a real cinema, a 3D environment where we watch a 2D movie_);
2. Your video already contains the movie theater in it (_everything the user will see around it is a video, as if you had recorded a video with a 360 camera inside a real movie theater_).

For both cases the video in question assisted is 2D.

Hope this helps.

**Comment by tomitrescak** [comment]
@ErickSimoes I'm after 3D video. But nevermind, I solved it and forgot to close the issue. It's actually super simple, with a video signals sent to each eye separately.
